### ISSUE TITLE
Azkaban3.x---实用的新特性

### ISSUE THREAD

**Issue by AronChung** [AronChung/blog#77]
### flow2.0
Azkaban 目前同时支持 Flow 1.0 和 Flow2.0 ，但是官方文档上更推荐使用Flow 2.0，因为Flow 1.0会在将来的版本被移除。Flow 2.0的主要设计思想是提供1.0所没有的流级定义。用户可以将属于给定流的所有job / properties文件合并到单个流定义文件中，其内容采用YAML语法进行定义，同时还支持在流中再定义流，称为为嵌入流或子流。

例如：
![image](https://user-images.githubusercontent.com/15808770/61119066-a29d1d00-a4cc-11e9-8152-b1646ae61725.png)
这个flow在1.0的写法需分为3个.job文件：
jobA.job
```
type=command
command=echo 'job A'
```
jobB.job
```
type=command
command=echo 'job B'
```
jobC.job
```
type=command
command=echo 'job C'
dependencies=jobA,jobB
```

但在flow2.0只需要一个.flow文件：
base.flow
```
nodes:
  - name: jobC
    type: command
    # jobC depends on jobA and jobB
    config: 
      command: echo "job C"
    dependsOn:
      - jobA
      - jobB

  - name: jobA
    type: command
    config:
      command: echo "job A"

  - name: jobB
    type: command
    config:
      command: echo "job B"
```

#### 嵌入flow
收缩效果
![image](https://user-images.githubusercontent.com/15808770/61119594-c6ad2e00-a4cd-11e9-8e4d-e77e876ba8ac.png)
展开效果
![image](https://user-images.githubusercontent.com/15808770/61119628-d62c7700-a4cd-11e9-909a-4068998388ac.png)
base.flow
```
nodes:
  - name: jobC
    type: noop
    dependsOn:
      - embedded_flow

  - name: embedded_flow
    type: flow
    config:
      prop: value
    nodes:
      - name: jobB
        type: noop
        dependsOn:
          - jobA

      - name: jobA
        type: command
        config:
          command: echo 'test'
```

#### Condition
可根据条件判断是否需要执行当前job
![image](https://user-images.githubusercontent.com/15808770/61119744-17bd2200-a4ce-11e9-9b19-9054fea2fa32.png)
base.flow
```
nodes:
 - name: JobA
   type: command
   config:
     command: sh /Users/aronchung/Downloads/conditionalFlowProject/write_to_props.sh

 - name: JobB
   type: command
   dependsOn:
     - JobA
   config:
     command: echo “This is JobB.”
   condition: ${JobA:param1} == 1

 - name: JobC
   type: command
   dependsOn:
     - JobA
   config:
     command: echo “This is JobC.”
   condition: ${JobA:param1} == 2

 - name: JobD
   type: command
   dependsOn:
     - JobB
     - JobC
   config:
     command: pwd
   condition: one_success
```
write_to_props.sh
`echo '{"param1":"1"}' > $JOB_OUTPUT_PROP_FILE`

> JOB_OUTPUT_PROP_FILE是一个环境变量参数,可以将参数传递到下游,以${jobName:param}的方式获取value
注意：写到${JOB_OUTPUT_PROP_FILE}临时文件中参数需要是json格式的，否则会报json解析错。

#### flow trigger schedule
通过上游写入kafka,下游查询kafka对应topic的对应内容规则,来触发下游的flow运行，可任意跨project
